version: '2'
services:
  messagebus:
    build:
      context: .
      args:
        SERVICE_NAME: messagebus
    volumes:
      - ./messagebus:/go/src/github.com/danielcuervo/wawi/messagebus
    ports:
      - "800:80"


  kafka:
    image: spotify/kafka
    ports:
      - "2181:2181"
      - "9092:9092"


