version: '2'
services:
  messenger:
    image: lejianaranja/golang:latest
    volumes:
      - ./messenger:/go/src/code
    ports:
      - "800:80"

  budgeteer:
    image: lejianaranja/golang:latest
    volumes:
      - ./budgeteer:/go/src/code
    ports:
      - "801:80"

  accountant:
    image: lejianaranja/golang:latest
    volumes:
      - ./accountant:/go/src/code
    ports:
      - "802:80"

