version: '2'
services:
  messenger:
    image: lejianaranja/golang:latest
    volumes:
      - ./messenger:/go/src/code
    ports:
      - "800:80"

  inventory:
    image: lejianaranja/golang:latest
    volumes:
      - ./inventory:/go/src/code
    ports:
      - "801:80"

  logistics:
    image: lejianaranja/golang:latest
    volumes:
      - ./logistics:/go/src/code
    ports:
      - "802:80"

  kafka:
    image: spotify/kafka
    ports:
      - "2181:2181"
      - "9092:9092"


